name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set PSRepository to Trusted for PowerShell Gallery
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      - name: Install ImportExcel module
        shell: pwsh
        run: |
          Install-Module -Name ImportExcel -Repository PSGallery -Force
      - name: Test Module Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest .\Veeam.Documentor.psd1
      - name: Publish module to PowerShell Gallery
        shell: pwsh
        run: |
          Publish-Module -Path ./ -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }} -Verbose